In [5]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import re
%matplotlib inline
import datetime
import random
import json
from IPython.display import display

In [2]:
columns = ["ALB","BUN","CRE","CRP","Ca","Cl","IP","K","Na","T-CHO","PCR", "TP"]
columns_value = [5,30,20,10,30,60,80,5,17,20,700,6]

In [3]:

def gen_dummy_df(columns, columns_value,  date_len):
    columns_len = len(columns)
    day_rand_i = np.random.randint(300)
    date_index = [datetime.date.today() + datetime.timedelta(weeks=52, days=day_rand_i + i)  for i in range(date_len)]
    base_df = pd.DataFrame(np.random.randn(date_len,columns_len), index=date_index)
    base_df = base_df.apply(lambda x : (1.2 + x / 3) * columns_value[x.name], axis=0)
    base_df = base_df.applymap(lambda x: np.nan if np.random.randint(0,10) == 0 else x)
    base_df.columns = columns
    return  base_df
    
def gen_dummy_patient_datasets(patient_num, columns=columns):
    columns = ["ALB","BUN","CRE","CRP","Ca","Cl","IP","K","Na","T-CHO","PCR", "TP"]
    columns_value = [5,30,20,10,30,60,80,5,17,20,700,6]
    head_dir = "./PatientsDataset"
    if not os.path.exists(head_dir):
        os.mkdir(head_dir)
    patient_dir_base = "patient{}"
    normal_file = "normal.csv"
    info_file = "info.json"
    exp_html_file = "exp.html"
    exp_json_file = "exp.json"
    once = True
    for i in range(patient_num):
        patient_id = i + 10000
        patient_dir = os.path.join(head_dir ,patient_dir_base.format(patient_id))
        normal_path = os.path.join(patient_dir, normal_file)
        info_path = os.path.join(patient_dir, info_file)
        exp_html_path = os.path.join(patient_dir, exp_html_file)
        exp_json_path = os.path.join(patient_dir, exp_json_file)
        if not os.path.exists(patient_dir):
            os.mkdir(patient_dir)
        date_len = np.random.randint(8,15)
        # save normal.csv
        dummy_patient_df = gen_dummy_df(columns, columns_value, date_len)
        if once:
            display(dummy_patient_df)
            once = False
        dummy_patient_df.to_csv(normal_path)
        # save info.json
        nonnephs_proba = np.random.rand()
        nephs_proba = 1- nonnephs_proba
        is_nephrosis = np.random.randint(0,2)
        info = {
            "patient_id" : patient_id,
            "is_nephrosis" : is_nephrosis,
            "nephs_proba" : nephs_proba,
            "nonnephs_proba" : nonnephs_proba,
            "predict_is_nephrosis" : nephs_proba > nonnephs_proba,
        }
        with open(info_path, "w") as f:
            json.dump(info, f, indent=4)
        # save exps
        exp_html = "<h1> patient{} exp.html </h1>".format(patient_id)
        with open(exp_html_path, "w") as f:
            f.write(exp_html)
        exp_json = {item : np.random.rand() for item in random.sample(columns, 5)}
        with open(exp_json_path, "w") as f:
            json.dump(exp_json, f, indent=4)

In [6]:
gen_dummy_patient_datasets(10)

,ALB,BUN,CRE,CRP,Ca,Cl,IP,K,Na,T-CHO,PCR,TP
2020-08-08,3.067115,34.662536,30.466326,16.505967,49.910552,43.506800,106.409105,5.198666,18.265387,27.120628,943.330343,3.512931
2020-08-09,6.129220,57.331750,NaN,17.582046,27.975241,96.572977,80.033052,8.827595,20.165440,15.879986,909.787590,6.948613
2020-08-10,6.989798,24.896026,26.159381,7.693937,9.179462,NaN,NaN,8.958048,15.359816,19.294342,598.392383,6.081816
2020-08-11,5.347823,29.165266,21.025520,13.502188,30.530495,73.169232,126.790934,7.859408,18.872604,NaN,823.864394,7.597813
2020-08-12,4.014193,37.656729,19.658438,15.955920,41.346313,88.737238,66.438695,5.149555,25.629568,NaN,875.508469,10.748698
2020-08-13,6.211033,30.550366,NaN,NaN,43.482421,56.541849,95.214497,4.671270,19.863024,21.504582,749.264428,3.965390
2020-08-14,5.038513,32.232989,13.818690,NaN,31.866310,86.821639,109.850720,4.537255,10.344391,20.101276,577.931441,9.077892
2020-08-15,3.325996,NaN,35.032670,6.689819,38.154761,80.063619,NaN,8.532011,22.846963,28.941763,812.546875,5.051086
2020-08-16,6.929637,59.441407,23.613843,4.049573,40.073036,63.966834,NaN,3.183707,17.707469,10.242003,1138.553468,7.356140
2020-08-17,NaN,39.027146,17.825920,15.790942,NaN,56.200699,115.824590,8.378285,17.115809,27.865752,842.441468,6.246902

In [160]:
head_dir = "./PatientsDataset"
info_file = "info.json"

1

In [18]:
base_df = pd.DataFrame(np.random.randn(8,12))

In [19]:
base_df.applymap(lambda x : 0 if x < 0 else x)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.704135,1.765880,0.217670,0.000000,0.000000,0.000000,0.000000,0.183639,1.471663,0.000000,0.000000,0.235496
1,0.000000,0.457155,0.431888,1.037700,1.594863,0.000000,0.000000,0.177284,0.300238,2.028595,0.604487,0.000000
2,0.188813,0.000000,1.161072,0.000000,0.566924,1.114493,0.000000,0.176923,0.000000,2.324996,0.000000,0.000000
3,0.159471,0.337206,0.607747,0.000000,0.411056,0.000000,0.355755,0.716188,0.172430,1.331181,0.564152,0.000000
4,0.825712,0.000000,0.000000,1.158217,0.000000,0.360156,0.011517,0.281693,1.184459,0.000000,0.575622,1.957244
5,0.145029,0.246832,1.094622,0.000000,0.000000,1.689844,0.000000,0.000000,1.103444,0.282727,0.637995,0.000000
6,1.850299,0.799741,0.217511,2.200301,0.202230,0.613502,0.046760,0.000000,0.580843,0.543473,0.125477,0.417109
7,0.000000,0.000000,0.000000,0.142789,0.000000,1.324580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [10]:
base_df = pd.DataFrame(np.random.randn(date_len,columns_len), index=date_index)
base_df = base_df.apply(lambda x : (1.2 + x / 3) * columns_value[x.name] if not  np.random.randint(0,10) == 0 else np.nan , axis=0)
# base_df.columns = columns

NameError: name 'columns_len' is not defined

In [186]:
s = base_df["ALB"]

In [188]:
for k,v in s.items():
    print(k,v)

2019-11-14 4.80384279758897
2019-11-15 6.656200069035081
2019-11-16 5.9136744421675225
2019-11-17 6.299186531786901
2019-11-18 8.692357802786335
2019-11-19 8.573379494738898
2019-11-20 7.245569703833369
2019-11-21 6.256990412314506

In [185]:
for w in base_df:
    for x in base_df[w]:
        print(x)

4.80384279758897
6.656200069035081
5.9136744421675225
6.299186531786901
8.692357802786335
8.573379494738898
7.245569703833369
6.256990412314506
31.919847977371724
25.980138456078517
32.43173048701244
45.623376479695715
38.925410020051004
49.79347109842402
42.83216541750184
37.949875100028905
25.58849005457492
18.36074242692519
21.92120177076383
31.198712608954846
32.412776994105116
32.49177571821134
26.31455715065355
30.79610753644641
12.871694968327374
12.073617487114054
11.073576422572806
8.868799734512717
11.101054019035324
19.29521599225449
15.60036470048792
11.261551124480349
35.98833575700037
35.077896652679904
31.877085715207706
29.967709904008988
58.86060784769509
31.797623229121285
47.78388966325604
46.12915807540681
74.39023700901943
65.27780658953702
79.28940554542028
74.40330894960961
79.334039724068
39.27319166072638
57.79198847404963
47.38198659147939
22.026529570724193
43.95915606382496
153.3579674544594
90.4209923657043
115.53833851658445
60.07539789583616
109.0021704782592
74.60261897756493
6.5117047791946625
5.17247792957982
9.398037146428651
5.329459721326206
4.630963780390118
4.016278549443468
7.644394421992243
6.111788315849436
26.59734068011157
19.071188878618937
11.141624988130346
22.839845945813092
19.35798415767022
23.82306269274898
17.973125536879035
17.762358731684337
14.386669137357675
17.282228178356434
18.06557765555141
16.237777068033896
22.107784884536393
23.066816866233616
22.41330922546103
34.674195620627565
994.9670977782683
610.3048154436796
963.3037707731067
1032.8983191492862
508.0010313331086
986.6510297229529
926.0891390090401
723.3298379437863
8.073687554262362
7.895959356421957
8.254698958268285
4.232954426683798
5.1103050244459105
10.548274621706188
5.724739991138817
9.236579973311713

In [ ]:
アルファベット
/
\*
[^*]
[^/]
・

演算子
*
+
()

In [2]:
import pandas as pd
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [5]:
iris_df.to_html("iris.html")

In [32]:
basehtml = """
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample</title>
    <!-- BootstrapのCSS読み込み -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
  </head>
  <body>
    {table}
  </body>
</html>
"""

In [36]:
# html = basehtml.format(table=iris_df.to_html(classes=["table", "table-bordered", "table-hover"]))
iris_style = iris_df.T.style.background_gradient(cmap="Blues")
html = iris_style.render()

In [37]:
with open("blueiris.html", "w") as f:
    anshtml = basehtml.format(table=html)
    f.write(anshtml)

In [17]:
iris_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
a = """
dafadfag
{arg}
fdasf
"""

a.format(arg="ssss")

'\ndafadfag\nssss\nfdasf\n'

In [46]:
a = range(10,21,5)

In [47]:
list(a)

[10, 15, 20]

In [62]:
params_dicts={"all_num":[8,12], "h_units": list(range(10,21,5)), "dropput":[0.2, 0.3]}

In [76]:
import itertools
keys = params_dicts.keys()
values_list = params_dicts.values()
for values in  itertools.product(*values_list):
    param_dict = {key : value for key, value in zip(keys, list(values))}
    print(param_dict)

{'all_num': 8, 'h_units': 10, 'dropput': 0.2}
{'all_num': 8, 'h_units': 10, 'dropput': 0.3}
{'all_num': 8, 'h_units': 15, 'dropput': 0.2}
{'all_num': 8, 'h_units': 15, 'dropput': 0.3}
{'all_num': 8, 'h_units': 20, 'dropput': 0.2}
{'all_num': 8, 'h_units': 20, 'dropput': 0.3}
{'all_num': 12, 'h_units': 10, 'dropput': 0.2}
{'all_num': 12, 'h_units': 10, 'dropput': 0.3}
{'all_num': 12, 'h_units': 15, 'dropput': 0.2}
{'all_num': 12, 'h_units': 15, 'dropput': 0.3}
{'all_num': 12, 'h_units': 20, 'dropput': 0.2}
{'all_num': 12, 'h_units': 20, 'dropput': 0.3}

In [55]:
def grid_serach(model)